// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartShelf_context_index from "./islands/AddToCartShelf/context/index.tsx";
import * as $AddToCartShelf_context_types from "./islands/AddToCartShelf/context/types.ts";
import * as $AddToCartShelf_index from "./islands/AddToCartShelf/index.tsx";
import * as $KitLook from "./islands/KitLook.tsx";
import * as $KitShelfInfo_index from "./islands/KitShelfInfo/index.tsx";
import * as $KitShelfInfo_types from "./islands/KitShelfInfo/types.ts";
import * as $LoginButton_index from "./islands/LoginButton/index.tsx";
import * as $ProductCompositionKit from "./islands/ProductCompositionKit.tsx";
import * as $ShelfProducts_context_index from "./islands/ShelfProducts/context/index.tsx";
import * as $ShelfProducts_context_types from "./islands/ShelfProducts/context/types.ts";
import * as $ShelfProducts_index from "./islands/ShelfProducts/index.tsx";
import * as $VideoIsland from "./islands/VideoIsland.tsx";
import * as $functions_headerFunctions from "./islands/functions/headerFunctions.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartShelf/context/index.tsx": $AddToCartShelf_context_index,
    "./islands/AddToCartShelf/context/types.ts": $AddToCartShelf_context_types,
    "./islands/AddToCartShelf/index.tsx": $AddToCartShelf_index,
    "./islands/KitLook.tsx": $KitLook,
    "./islands/KitShelfInfo/index.tsx": $KitShelfInfo_index,
    "./islands/KitShelfInfo/types.ts": $KitShelfInfo_types,
    "./islands/LoginButton/index.tsx": $LoginButton_index,
    "./islands/ProductCompositionKit.tsx": $ProductCompositionKit,
    "./islands/ShelfProducts/context/index.tsx": $ShelfProducts_context_index,
    "./islands/ShelfProducts/context/types.ts": $ShelfProducts_context_types,
    "./islands/ShelfProducts/index.tsx": $ShelfProducts_index,
    "./islands/VideoIsland.tsx": $VideoIsland,
    "./islands/functions/headerFunctions.tsx": $functions_headerFunctions,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
